version: '3'
services:
  ritar-bms:
    build: 
      context: .
    restart: unless-stopped
    privileged: true
    volumes:
      - ./config.yaml:/workdir/config.yaml
      - /dev:/dev
    devices:
      - /dev/ttyUSB0:/dev/ttyUSB0
      - /dev/ttyUSB1:/dev/ttyUSB1
  
